// Copyright 2026
//
// Internal, opt-in encoder stage profiling.

#ifndef WEBP_ENC_PROFILE_ENC_H_
#define WEBP_ENC_PROFILE_ENC_H_

#include <stddef.h>
#include <stdint.h>

#include "src/webp/encode.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  WEBP_PROFILE_LOSSLESS_PREPARE = 0,
  WEBP_PROFILE_LOSSLESS_CONTAINER_SETUP,
  WEBP_PROFILE_LOSSLESS_ANALYZE,
  WEBP_PROFILE_LOSSLESS_ENCODER_INIT,
  WEBP_PROFILE_LOSSLESS_PALETTE,
  WEBP_PROFILE_LOSSLESS_INPUT_COPY,
  WEBP_PROFILE_LOSSLESS_SUBTRACT_GREEN,
  WEBP_PROFILE_LOSSLESS_PREDICTOR,
  WEBP_PROFILE_LOSSLESS_CROSS_COLOR,
  WEBP_PROFILE_LOSSLESS_HASH_CHAIN,
  WEBP_PROFILE_LOSSLESS_BACKWARD_REFS,
  WEBP_PROFILE_LOSSLESS_HISTOGRAM,
  WEBP_PROFILE_LOSSLESS_HUFFMAN,
  WEBP_PROFILE_LOSSLESS_BITSTREAM,
  WEBP_PROFILE_LOSSLESS_STREAM_FINALIZE,
  WEBP_PROFILE_LOSSLESS_RIFF_WRITE,
  WEBP_PROFILE_BACKREF_COST_DP_TOTAL,
  WEBP_PROFILE_BACKREF_COST_DP_SETUP,
  WEBP_PROFILE_BACKREF_COST_DP_STEADY,
  WEBP_PROFILE_BACKREF_COST_TRACEBACK,
  WEBP_PROFILE_BACKREF_COST_MATERIALIZE,
  WEBP_PROFILE_METAL_INIT,
  WEBP_PROFILE_METAL_CROSS_COLOR_DISPATCH,
  WEBP_PROFILE_METAL_HASH_PIPELINE_INIT,
  WEBP_PROFILE_METAL_HASH_DISPATCH,
  WEBP_PROFILE_LOSSY_IMPORT,
  WEBP_PROFILE_LOSSY_ENCODER_INIT,
  WEBP_PROFILE_LOSSY_ANALYZE,
  WEBP_PROFILE_LOSSY_STAT_LOOP,
  WEBP_PROFILE_LOSSY_ENCODE_LOOP,
  WEBP_PROFILE_LOSSY_ALPHA,
  WEBP_PROFILE_LOSSY_WRITE,
  WEBP_PROFILE_STAGE_COUNT
} WebPProfileStage;

// This internal API is compiled only for the encoder-stage-profile experiment.
#if defined(WEBP_USE_ENCODER_STAGE_PROFILE_EXPERIMENT) ||       \
    defined(WEBP_BACKREF_COST_ATTRIBUTION_V1_MARKERS) ||        \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V2_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V3_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V4_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V5_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V6_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V7_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V8_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V9_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V10_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V11_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V12_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V13_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V14_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V15_EXPERIMENT)
void WebPProfileBeginSession(const WebPConfig* config,
                             const WebPPicture* picture);
void WebPProfileEndSession(int ok, int error_code);
uint64_t WebPProfileStageBegin(WebPProfileStage stage);
void WebPProfileStageEnd(WebPProfileStage stage, uint64_t start_ns);
void WebPProfileSetOutputSize(size_t output_size);
void WebPProfileMarkMetalCrossColor(void);
void WebPProfileMarkMetalHash(void);
#if defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V3_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V4_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V5_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V6_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V7_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V8_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V9_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V10_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V11_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V12_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V13_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V14_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V15_EXPERIMENT)
uint64_t WebPProfileClockNowForValidation(void);
#endif
#else
// Default builds compile every call site to a no-op and omit profile_enc.c.
#define WebPProfileBeginSession(config, picture) \
  ((void)(config), (void)(picture))
#define WebPProfileEndSession(ok, error_code) ((void)(ok), (void)(error_code))
#define WebPProfileStageBegin(stage) ((void)(stage), (uint64_t)0)
#define WebPProfileStageEnd(stage, start_ns) ((void)(stage), (void)(start_ns))
#define WebPProfileSetOutputSize(output_size) ((void)(output_size))
#define WebPProfileMarkMetalCrossColor() ((void)0)
#define WebPProfileMarkMetalHash() ((void)0)
#endif

#if defined(WEBP_BACKREF_COST_ATTRIBUTION_V1_MARKERS) ||        \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V2_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V3_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V4_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V5_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V6_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V7_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V8_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V9_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V10_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V11_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V12_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V13_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V14_EXPERIMENT) || \
    defined(WEBP_USE_BACKREF_COST_ATTRIBUTION_V15_EXPERIMENT)
#if defined(_MSC_VER)
#define WEBP_PROFILE_NOINLINE __declspec(noinline)
#elif defined(__GNUC__) || defined(__clang__)
#define WEBP_PROFILE_NOINLINE __attribute__((noinline))
#else
#define WEBP_PROFILE_NOINLINE
#endif
#else
#define WEBP_PROFILE_NOINLINE
#endif

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // WEBP_ENC_PROFILE_ENC_H_
